/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./../components/AppIcon.vue')['default']
    AppLayout: typeof import('./../components/AppLayout.vue')['default']
    EmptyState: typeof import('./../components/EmptyState.vue')['default']
    FullPageSpinner: typeof import('./../components/FullPageSpinner.vue')['default']
    LoadingSpinner: typeof import('./../components/LoadingSpinner.vue')['default']
    MetricCard: typeof import('./../components/MetricCard.vue')['default']
    PageHeader: typeof import('./../components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    ToastContainer: typeof import('./../components/ToastContainer.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
