/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityCenter: typeof import('./../components/layout/ActivityCenter.vue')['default']
    AdminHomeActivityFeed: typeof import('./../components/adminHome/AdminHomeActivityFeed.vue')['default']
    AdminHomeRunList: typeof import('./../components/adminHome/AdminHomeRunList.vue')['default']
    AdminRunDetailPanel: typeof import('./../components/admin/AdminRunDetailPanel.vue')['default']
    AdminWorkspaceHero: typeof import('./../components/admin/AdminWorkspaceHero.vue')['default']
    AppIcon: typeof import('./../components/AppIcon.vue')['default']
    AppLayout: typeof import('./../components/AppLayout.vue')['default']
    AppSidebar: typeof import('./../components/layout/AppSidebar.vue')['default']
    AuthShowcase: typeof import('./../components/auth/AuthShowcase.vue')['default']
    BenchmarkSegmentSection: typeof import('./../components/benchmark/BenchmarkSegmentSection.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    CommandPalette: typeof import('./../components/layout/CommandPalette.vue')['default']
    ComparableCard: typeof import('./../components/ComparableCard.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataDatasetLibrary: typeof import('./../components/data/DataDatasetLibrary.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataUploadWorkspace: typeof import('./../components/data/DataUploadWorkspace.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EmptyState: typeof import('./../components/EmptyState.vue')['default']
    FeatureImportanceChart: typeof import('./../components/charts/FeatureImportanceChart.vue')['default']
    FilterBar: typeof import('./../components/FilterBar.vue')['default']
    FilterField: typeof import('./../components/FilterField.vue')['default']
    FullPageSpinner: typeof import('./../components/FullPageSpinner.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingSpinner: typeof import('./../components/LoadingSpinner.vue')['default']
    MapDetailDialog: typeof import('./../components/map/MapDetailDialog.vue')['default']
    MetricCard: typeof import('./../components/MetricCard.vue')['default']
    MunicipalityCard: typeof import('./../components/MunicipalityCard.vue')['default']
    MunicipalityCompareWorkspace: typeof import('./../components/municipalities/MunicipalityCompareWorkspace.vue')['default']
    PageHeader: typeof import('./../components/PageHeader.vue')['default']
    Password: typeof import('primevue/password')['default']
    PredictionComparables: typeof import('./../components/prediction/PredictionComparables.vue')['default']
    PredictionForm: typeof import('./../components/prediction/PredictionForm.vue')['default']
    PredictionResultSummary: typeof import('./../components/prediction/PredictionResultSummary.vue')['default']
    PriceDistributionChart: typeof import('./../components/charts/PriceDistributionChart.vue')['default']
    ProfileDialog: typeof import('./../components/layout/ProfileDialog.vue')['default']
    PropertyTypePieChart: typeof import('./../components/charts/PropertyTypePieChart.vue')['default']
    RegionBarChart: typeof import('./../components/charts/RegionBarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedWorkspaceMenu: typeof import('./../components/workbench/SavedWorkspaceMenu.vue')['default']
    SectionPanel: typeof import('./../components/SectionPanel.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tab: typeof import('primevue/tab')['default']
    TableWorkbenchToolbar: typeof import('./../components/workbench/TableWorkbenchToolbar.vue')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    TrendLineChart: typeof import('./../components/charts/TrendLineChart.vue')['default']
    WorkspaceTray: typeof import('./../components/layout/WorkspaceTray.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
