"""initial_tables

Revision ID: 7948cdf948fa
Revises:
Create Date: 2026-03-15 14:32:44.982760
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7948cdf948fa"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_name", sa.String(length=500), nullable=False),
        sa.Column("stored_path", sa.String(length=500), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("columns_json", sa.Text(), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dataset_files_file_hash"), "dataset_files", ["file_hash"], unique=False)
    op.create_table(
        "listings_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("overpriced_count", sa.Integer(), nullable=False),
        sa.Column("underpriced_count", sa.Integer(), nullable=False),
        sa.Column("market_aligned_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_csv_path", sa.String(length=500), nullable=True),
        sa.Column("rows", sa.Integer(), nullable=True),
        sa.Column("mae", sa.Float(), nullable=True),
        sa.Column("rmse", sa.Float(), nullable=True),
        sa.Column("r2", sa.Float(), nullable=True),
        sa.Column("features_json", sa.Text(), nullable=True),
        sa.Column("importance_json", sa.Text(), nullable=True),
        sa.Column("trained_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prediction_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("predicted_price_eur", sa.Float(), nullable=True),
        sa.Column("used_features_json", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prediction_logs_created_at"),
        "prediction_logs",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "region_lookup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obcina_sifra", sa.String(length=10), nullable=True),
        sa.Column("obcina_naziv", sa.String(length=200), nullable=False),
        sa.Column("eid_statisticna_regija", sa.String(length=50), nullable=True),
        sa.Column("regija_naziv", sa.String(length=200), nullable=False),
        sa.Column("vir", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_region_lookup_obcina_naziv"),
        "region_lookup",
        ["obcina_naziv"],
        unique=False,
    )
    op.create_index(
        op.f("ix_region_lookup_obcina_sifra"),
        "region_lookup",
        ["obcina_sifra"],
        unique=False,
    )
    op.create_table(
        "training_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("stage", sa.String(length=100), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("csv_path", sa.String(length=500), nullable=True),
        sa.Column("rows", sa.Integer(), nullable=True),
        sa.Column("fitted_trees", sa.Integer(), nullable=True),
        sa.Column("total_trees", sa.Integer(), nullable=True),
        sa.Column("trees_per_sec", sa.Float(), nullable=True),
        sa.Column("eta_sec", sa.Float(), nullable=True),
        sa.Column("duration_sec", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
    )
    op.create_index(
        op.f("ix_training_jobs_updated_at"),
        "training_jobs",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("admin", "viewer", name="userrole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_training_jobs_updated_at"), table_name="training_jobs")
    op.drop_table("training_jobs")
    op.drop_index(op.f("ix_region_lookup_obcina_sifra"), table_name="region_lookup")
    op.drop_index(op.f("ix_region_lookup_obcina_naziv"), table_name="region_lookup")
    op.drop_table("region_lookup")
    op.drop_index(op.f("ix_prediction_logs_created_at"), table_name="prediction_logs")
    op.drop_table("prediction_logs")
    op.drop_table("model_runs")
    op.drop_table("listings_runs")
    op.drop_index(op.f("ix_dataset_files_file_hash"), table_name="dataset_files")
    op.drop_table("dataset_files")
    # ### end Alembic commands ###
